<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class clasificador_presupuestario extends Seeder
{

    public function run()
    {
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.01.00','descripcion'=>'Sueldos básicos personal fijo a tiempo completo','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.03.00','descripcion'=>'Suplencias al personal empleado','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.10.00','descripcion'=>'Salarios al personal obrero en puestos permanentes a tiempo completo','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.13.00','descripcion'=>'Suplencias al personal obrero','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.18.01','descripcion'=>'Remuneraciones al personal contratado a tiempo determinado','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.18.02','descripcion'=>'Remuneraciones por honorarios profesionales','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.02.00','descripcion'=>'Primas de transporte al personal empleado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.08.00','descripcion'=>'Primas de profesionalización al personal empleado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.09.00','descripcion'=>'Primas por antigüedad al personal empleado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.10.00','descripcion'=>'Primas por jerarquía o responsabilidad en el cargo','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.21.00','descripcion'=>'Primas por antigüedad al personal obrero','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.97.00','descripcion'=>'Otras primas al personal empleado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.03.98.00','descripcion'=>'Otras primas al personal obrero','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.01.00','descripcion'=>'Complemento al personal empleado por horas extraordinarias o por sobre tiempo','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.02.00','descripcion'=>'Complemento al personal empleado por trabajo nocturno','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.07.00','descripcion'=>'Bonificación al personal empleado','agrupacion'=>'']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.08.00','descripcion'=>'Bono compensatorio de alimentación al personal empleado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.14.00','descripcion'=>'Complemento al personal obrero por horas extraordinarias o por sobre tiempo','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.15.00','descripcion'=>'Complemento al personal obrero por trabajo o jornada nocturna','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.18.00','descripcion'=>'Bono compensatorio de alimentación al personal obrero','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.24.00','descripcion'=>'Complemento al personal contratado por horas extraordinarias o por sobre tiempo','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.26.00','descripcion'=>'Bono compensatorio de alimentación al personal contratado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.50.00','descripcion'=>'Bonificación al personal de alto nivel y de dirección','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.96.00','descripcion'=>'Otros complementos al personal empleado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.97.00','descripcion'=>'Otros complementos al personal obrero','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.04.98.00','descripcion'=>'Otros complementos al personal contratado','agrupacion'=>'BENEFICIOS Y COMPLEMENTOS DE SUELDOS Y SALARIOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.03.00','descripcion'=>'Bono vacacional al personal empleado','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.06.00','descripcion'=>'Bono vacacional al personal obrero','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.08.00','descripcion'=>'Bono vacacional al personal contratado','agrupacion'=>'SUELDOS, SALARIOS Y OTRAS RETRIBUCIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.01.00','descripcion'=>'Aporte patronal al Instituto Venezolano de los Seguros Sociales (I.V.S.S.) al personal empleado','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.04.00','descripcion'=>'Aporte patronal al Fondo Contributivo del Régimen Prestacional de Empleo al personal empleado','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.05.00','descripcion'=>'Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda al personal empleado','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.06.00','descripcion'=>'Aporte patronal al Instituto Nacional de Capacitación y Educación Socialista (Inces) al personal empleado','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.10.00','descripcion'=>'Aporte patronal al Instituto Venezolano de los Seguros Sociales (I.V.S.S.) al personal obrero','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.12.00','descripcion'=>'Aporte patronal al Fondo Contributivo del Régimen Prestacional de Empleo al personal obrero','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.13.00','descripcion'=>'Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda al personal obrero','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.14.00','descripcion'=>'Aporte patronal al Instituto Nacional de Capacitación y Educación Socialista (Inces) al personal obrero','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.29.00','descripcion'=>'Aporte patronal al Instituto Nacional de Capacitación y Educación Socialista (Inces) por personal contratado','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.44.00','descripcion'=>'Aporte patronal al Instituto Nacional de Capacitación y Educación Socialista (Inces) por personal de alto nivel y de dirección','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.06.96.00','descripcion'=>'Otros aportes patronales al personal empleado','agrupacion'=>'APORTES PATRONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.02.00','descripcion'=>'Becas al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.03.00','descripcion'=>'Ayudas por matrimonio al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.04.00','descripcion'=>'Ayudas por nacimiento de hijos e hijas al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.05.00','descripcion'=>'Ayudas por defunción al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.06.00','descripcion'=>'Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.07.00','descripcion'=>'Aporte patronal a cajas de ahorro al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.08.00','descripcion'=>'Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.09.00','descripcion'=>'Ayudas al personal empleado para adquisición de uniformes y útiles escolares de sus hijos e hijas','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.10.00','descripcion'=>'Dotación de uniformes al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.11.00','descripcion'=>'Aporte patronal para gastos de guarderías y preescolar para hijos e hijas del personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.12.00','descripcion'=>'Aportes para la adquisición de juguetes para los hijos e hijas del personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.18.00','descripcion'=>'Becas al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.19.00','descripcion'=>'Ayudas por matrimonio al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.20.00','descripcion'=>'Ayudas por nacimiento de hijos e hijas al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.21.00','descripcion'=>'Ayudas por defunción al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.22.00','descripcion'=>'Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.23.00','descripcion'=>'Aporte patronal a cajas de ahorro al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.24.00','descripcion'=>'Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.25.00','descripcion'=>'Ayudas al personal obrero para adquisición de uniformes y útiles escolares de sus hijos e hijas','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.26.00','descripcion'=>'Dotación de uniformes al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.27.00','descripcion'=>'Aporte patronal para gastos de guarderías y preescolar para hijos e hijas del personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.28.00','descripcion'=>'Aportes para la adquisición de juguetes para los hijos e hijas del personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.96.00','descripcion'=>'Otras subvenciones al personal empleado','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.07.97.00','descripcion'=>'Otras subvenciones al personal obrero','agrupacion'=>'ASISTENCIA SOCIOECONÓMICA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.08.01.00','descripcion'=>'Prestaciones sociales e indemnizaciones al personal empleado','agrupacion'=>'PRESTACIONES SOCIALES Y OTRAS INDEMNIZACIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.08.02.00','descripcion'=>'Prestaciones sociales e indemnizaciones al personal obrero','agrupacion'=>'PRESTACIONES SOCIALES Y OTRAS INDEMNIZACIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.08.03.00','descripcion'=>'Prestaciones sociales e indemnizaciones al personal contratado','agrupacion'=>'PRESTACIONES SOCIALES Y OTRAS INDEMNIZACIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.01.01.00','descripcion'=>'Alimentos y bebidas para personas','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.02.02.00','descripcion'=>'Petróleo crudo y gas natural','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.03.01.00','descripcion'=>'Textiles','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.03.02.00','descripcion'=>'Prendas de vestir','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.04.03.00','descripcion'=>'Cauchos y tripas para vehículos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.01.00','descripcion'=>'Pulpa de madera, papel y cartón','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.02.00','descripcion'=>'Envases y cajas de papel y cartón','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.03.00','descripcion'=>'Productos de papel y cartón para oficina','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.04.00','descripcion'=>'Libros, revistas y periódicos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.05.00','descripcion'=>'Material de enseñanza','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.06.00','descripcion'=>'Productos de papel y cartón para computación','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.05.07.00','descripcion'=>'Productos de papel y cartón para la imprenta y reproducción','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.06.01.00','descripcion'=>'Sustancias químicas y de uso industrial','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.06.02.00','descripcion'=>'Abonos, plaguicidas y otros','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.06.03.00','descripcion'=>'Tintas, pinturas y colorantes','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.06.04.00','descripcion'=>'Productos farmacéuticos y medicamentos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.06.06.00','descripcion'=>'Combustibles y lubricantes','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.06.08.00','descripcion'=>'Productos plásticos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.07.02.00','descripcion'=>'Vidrios y productos de vidrio','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.07.04.00','descripcion'=>'Cemento, cal y yeso','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.01.00','descripcion'=>'Productos primarios de hierro y acero','agrupacion'=>'BIENES DE CONSUMO (GASTOS  CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.02.00','descripcion'=>'Productos de metales no ferrosos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.03.00','descripcion'=>'Herramientas menores, cuchillería y artículos generales de ferretería','agrupacion'=>'BIENES DE CONSUMO (GASTOS  CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.04.00','descripcion'=>'Productos metálicos estructurales','agrupacion'=>'BIENES DE CONSUMO (GASTOS  CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.07.00','descripcion'=>'Material de señalamiento','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.09.00','descripcion'=>'Repuestos y accesorios para equipos de transporte','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.08.10.00','descripcion'=>'Repuestos y accesorios para otros equipos','agrupacion'=>'BIENES DE CONSUMO (GASTOS  CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.09.01.00','descripcion'=>'Productos primarios de madera','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.01.00','descripcion'=>'Artículos de deporte, recreación y juguetes','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.02.00','descripcion'=>'Materiales y útiles de limpieza y aseo','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.03.00','descripcion'=>'Utensilios de cocina y comedor','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.04.00','descripcion'=>'Útiles menores médico - quirúrgicos de laboratorio, dentales y de veterinaria','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.05.00','descripcion'=>'Útiles de escritorio, oficina y materiales de instrucción','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.06.00','descripcion'=>'Condecoraciones, ofrendas y similares','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.07.00','descripcion'=>'Productos de seguridad en el trabajo','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.08.00','descripcion'=>'Materiales para equipos de computación','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.09.00','descripcion'=>'Especies timbradas y valores','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.11.00','descripcion'=>'Materiales eléctricos','agrupacion'=>'BIENES DE CONSUMO (GASTOS  CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.12.00','descripcion'=>'Materiales para instalaciones sanitarias','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.13.00','descripcion'=>'Materiales fotográficos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.10.99.00','descripcion'=>'Otros productos y útiles diversos','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.11.01.00','descripcion'=>'Productos y artículos para la venta','agrupacion'=>'BIENES Y SERVICIOS PARA LA VENTA']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.01.01.00','descripcion'=>'Alquileres de edificios y locales','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.01.03.00','descripcion'=>'Alquileres de tierras y terrenos','agrupacion'=>'ALQUILERES DE TIERRAS Y TERRENOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.02.01.00','descripcion'=>'Alquileres de maquinaria y demás equipos de construcción, campo, industria y taller','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.02.02.00','descripcion'=>'Alquileres de equipos de transporte, tracción y elevación','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.02.03.00','descripcion'=>'Alquileres de equipos de comunicaciones y de señalamiento','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.02.06.00','descripcion'=>'Alquileres de máquinas, muebles y demás equipos de oficina y alojamiento','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.02.99.00','descripcion'=>'Alquileres de otras maquinaria y equipos','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.03.03.00','descripcion'=>'Paquetes y programas de computación','agrupacion'=>'DERECHOS SOBRE BIENES INTANGIBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.03.04.00','descripcion'=>'Concesión de bienes y servicios','agrupacion'=>'DERECHOS SOBRE BIENES INTANGIBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.02.00','descripcion'=>'Gas','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.03.00','descripcion'=>'Agua','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.04.01','descripcion'=>'Servicios de telefonía prestados por organismos públicos','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.04.02','descripcion'=>'Servicios de telefonía prestados por instituciones privadas','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.05.00','descripcion'=>'Servicio de comunicaciones','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.06.00','descripcion'=>'Servicio de aseo urbano y domiciliario','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.07.00','descripcion'=>'Servicio de condominio','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.05.03.00','descripcion'=>'Servicio de administración, vigilancia y mantenimiento del servicio de agua','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.06.01.00','descripcion'=>'Fletes y embalajes','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.06.02.00','descripcion'=>'Almacenaje','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.06.03.00','descripcion'=>'Estacionamiento','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.06.04.00','descripcion'=>'Peaje','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.06.05.00','descripcion'=>'Servicios de protección en traslado de fondos y de mensajería','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.07.01.00','descripcion'=>'Publicidad y propaganda','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.07.02.00','descripcion'=>'Imprenta y reproducción','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.07.03.00','descripcion'=>'Relaciones sociales','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.07.04.00','descripcion'=>'Avisos','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.08.01.00','descripcion'=>'Primas y gastos de seguros','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.08.02.00','descripcion'=>'Comisiones y gastos bancarios','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.09.01.00','descripcion'=>'Viáticos y pasajes dentro del país','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.09.02.00','descripcion'=>'Viáticos y pasajes fuera del país','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.09.03.00','descripcion'=>'Asignación por kilómetros recorridos','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.01.00','descripcion'=>'Servicios jurídicos','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.03.00','descripcion'=>'Servicios de procesamiento de datos','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.04.00','descripcion'=>'Servicios de ingeniería y arquitectónicos','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.05.00','descripcion'=>'Servicios médicos, odontológicos y otros servicios de sanidad','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.07.00','descripcion'=>'Servicios de capacitación y adiestramiento','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.09.00','descripcion'=>'Servicios de lavandería y tintorería','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.10.00','descripcion'=>'Servicios de vigilancia y seguridad','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.11.00','descripcion'=>'Servicios para la elaboración y suministro de comida','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.99.00','descripcion'=>'Otros servicios profesionales y técnicos','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES (GASTOS CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.01.00','descripcion'=>'Conservación y reparaciones menores de maquinaria y demás equipos de construcción, campo, industria y taller','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES (GASTOS CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.02.00','descripcion'=>'Conservación y reparaciones menores de equipos de transporte, tracción y elevación','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES (GASTOS CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.03.00','descripcion'=>'Conservación y reparaciones menores de equipos de comunicaciones y de señalamiento','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.04.00','descripcion'=>'Conservación y reparaciones menores de equipos médico-quirúrgicos, dentales y de veterinaria','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.05.00','descripcion'=>'Conservación y reparaciones menores de equipos científicos, religiosos, de enseñanza y recreación','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.07.00','descripcion'=>'Conservación y reparaciones menores de máquinas, muebles y demás equipos de oficina y alojamiento','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.11.99.00','descripcion'=>'Conservación y reparaciones menores de otras maquinaria y equipos','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.12.01.00','descripcion'=>'Conservación y reparaciones menores de obras en bienes del dominio privado','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES (GASTOS CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.12.02.00','descripcion'=>'Conservación y reparaciones menores de obras en bienes del dominio público','agrupacion'=>'BIENES DE CONSUMO Y SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.15.01.00','descripcion'=>'Derechos de importación y servicios aduaneros','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.15.02.00','descripcion'=>'Tasas y otros derechos obligatorios','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.15.99.00','descripcion'=>'Otros servicios fiscales','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.16.01.00','descripcion'=>'Servicios de diversión, esparcimiento y culturales','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.18.01.00','descripcion'=>'Impuesto al valor agregado','agrupacion'=>'IMPUESTOS INDIRECTOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.19.01.00','descripcion'=>'Comisiones por servicios para cumplir con los beneficios sociales','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.99.01.00','descripcion'=>'Otros servicios no personales','agrupacion'=>'BIENES DE CONSUMO SERVICIOS NO PERSONALES (GASTOS CAPITALIZABLES)']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.01.01.01','descripcion'=>'Repuestos mayores para maquinaria y demás equipos de construcción, campo, industria y taller','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.01.01.02','descripcion'=>'Repuestos mayores para equipos de transporte, tracción y elevación','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.01.02.01','descripcion'=>'Reparaciones, mejoras y adiciones mayores de maquinaria y demás equipos de construcción, campo, industria y taller','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.01.02.02','descripcion'=>'Reparaciones, mejoras y adiciones mayores de equipos de transporte, tracción y elevación','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.02.01.00','descripcion'=>'Conservación, ampliaciones y mejoras mayores de obras en bienes del dominio privado','agrupacion'=>'CONSTRUCCIONES DE BIENES DE DOMINIO PRIVADO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.02.02.00','descripcion'=>'Conservación, ampliaciones y mejoras mayores de obras en bienes del dominio público','agrupacion'=>'CONSTRUCCIONES DE BIENES DE DOMINIO PÚBLICO SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.03.05.00','descripcion'=>'Maquinaria y equipos industriales y de taller','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.03.06.00','descripcion'=>'Maquinaria y equipos de energía','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.03.99.00','descripcion'=>'Otra maquinaria y demás equipos de construcción, campo, industria y taller','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.04.01.00','descripcion'=>'Vehículos automotores terrestres','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.05.01.00','descripcion'=>'Equipos de telecomunicaciones','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.05.02.00','descripcion'=>'Equipos de señalamiento','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.06.01.00','descripcion'=>'Equipos médico - quirúrgicos, dentales y de veterinaria','agrupacion'=>'SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.07.01.00','descripcion'=>'Equipos científicos y de laboratorio','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.07.02.00','descripcion'=>'Equipos de enseñanza, deporte y recreación','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.07.03.00','descripcion'=>'Obras de arte','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.09.01.00','descripcion'=>'Mobiliario y equipos de oficina','agrupacion'=>'BIENES DE CONSUMO MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES, SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.09.02.00','descripcion'=>'Equipos de computación','agrupacion'=>'BIENES DE CONSUMO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.09.03.00','descripcion'=>'Mobiliario y equipos de alojamiento','agrupacion'=>'MAQUINARIA, EQUIPOS Y OTROS BIENES MUEBLES SERVICIOS NO PERSONALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.11.01.00','descripcion'=>'Adquisición de tierras y terrenos','agrupacion'=>'TIERRAS Y TERRENOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.12.04.00','descripcion'=>'Paquetes y programas de computación','agrupacion'=>'BIENES INTANGIBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.12.05.00','descripcion'=>'Estudios y proyectos','agrupacion'=>'BIENES INTANGIBLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.14.01.00','descripcion'=>'Contratación de inspección de obras de bienes del dominio privado','agrupacion'=>'CONSTRUCCIONES DE BIENES DE DOMINIO PRIVADO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.15.06.00','descripcion'=>'Construcciones de edificaciones industriales','agrupacion'=>'CONSTRUCCIONES DE BIENES DE DOMINIO PRIVADO']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.07.01.01.01','descripcion'=>'Pensiones del personal empleado, obrero y militar','agrupacion'=>'PENSIONES Y OTROS BENEFICIOS ASOCIADOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.07.01.01.02','descripcion'=>'Jubilaciones del personal empleado, obrero y militar','agrupacion'=>'JUBILACIONES Y OTROS BENEFICIOS ASOCIADOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.07.01.01.75','descripcion'=>'Subsidios a organismos laborales y gremiales','agrupacion'=>'SUBSIDIOS A ORGANISMOS LABORALES Y GREMIALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.07.01.01.99','descripcion'=>'Otras transferencias corrientes internas al sector privado','agrupacion'=>'OTRAS TRANSFERENCIAS DIRECTAS A PERSONAS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.07.01.02.01','descripcion'=>'Donaciones corrientes a personas','agrupacion'=>'DONACIONES A PERSONAS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.02.01.00','descripcion'=>'Intereses por depósitos internos','agrupacion'=>'INTERESES POR DEPÓSITOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.02.03.00','descripcion'=>'Intereses por otros financiamientos','agrupacion'=>'INTERESES POR OTROS FINANCIAMIENTOS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.05.03.00','descripcion'=>'Indemnizaciones diversas','agrupacion'=>'INDEMNIZACIONES DIVERSAS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.06.02.00','descripcion'=>'Pérdidas en operaciones cambiarias','agrupacion'=>'PÉRDIDAS EN OPERACIONES CAMBIARIAS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.06.04.00','descripcion'=>'Pérdidas por cuentas incobrables','agrupacion'=>'CUENTAS INCOBRABLES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.07.01.00','descripcion'=>'Descuentos sobre ventas','agrupacion'=>'DESCUENTOS SOBRE VENTAS']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.08.01.03','descripcion'=>'Indemnizaciones por daños y perjuicios ocasionados por entes descentralizados con fines empresariales','agrupacion'=>'INDEMNIZACIONES POR DAÑOS Y PERJUICIOS OCASIONADOS POR ENTES DESCENTRALIZADOS SIN FINES EMPRESARIALES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.99.01.00','descripcion'=>'Otros gastos','agrupacion'=>'OTROS GASTOS CORRIENTES PRESTACIONES SOCIALES Y OTRAS INDEMNIZACIONES']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.04.01.00','descripcion'=>'Electricidad','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.01.00','descripcion'=>'Aguinaldos al personal empleado','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.07.00','descripcion'=>'Aguinaldos al personal contratado','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.05.00','descripcion'=>'Utilidades al personal obrero','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.05.02.00','descripcion'=>'Utilidades al personal empleado','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.01.01.19.00','descripcion'=>'Retribuciones por becas - salarios, bolsas de trabajo, pasantías y similares','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.01.01.05','descripcion'=>'','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.04.03.08.00','descripcion'=>'Equipos de almacén','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.99.01.00','descripcion'=>'Otros materiales y suministros','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.02.02.04.00','descripcion'=>'Mineral no ferroso','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.03.10.02.00','descripcion'=>'Servicios de contabilidad y auditoría','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.01.01.03','descripcion'=>'NULL','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.01.01.06','descripcion'=>'NULL','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.01.01.07','descripcion'=>'NULL','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.01.01.04','descripcion'=>'NULL','agrupacion'=>'NULL']);
        DB::table('clasificador_presupuestario')->insert(['codigo_partida'=>'4.08.01.01.02','descripcion'=>'NULL','agrupacion'=>'NULL']);
    }
}
