<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class municipio extends Seeder
{
    public function run()
    {
        DB::table('municipio')->insert(['id'=>101,'municipio'=>'Bolivariano Libertador','id_estado'=>1,]);
        DB::table('municipio')->insert(['id'=>201,'municipio'=>'Autonomo Alto Orinoco','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>202,'municipio'=>'Autonomo Atabapo','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>203,'municipio'=>'Autonomo Atures','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>204,'municipio'=>'Autonomo Autana','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>205,'municipio'=>'Autonomo Maroa','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>206,'municipio'=>'Autonomo Manapiare','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>207,'municipio'=>'Autonomo Río Negro','id_estado'=>2,]);
        DB::table('municipio')->insert(['id'=>301,'municipio'=>'Anaco','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>302,'municipio'=>'Aragua','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>303,'municipio'=>'Fernando De Peñalver','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>304,'municipio'=>'Francisco Del Carmen Carvajal','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>305,'municipio'=>'Francisco De Miranda','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>306,'municipio'=>'Guanta','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>307,'municipio'=>'Independencia','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>308,'municipio'=>'Juan Antonio Sotillo','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>309,'municipio'=>'Juan Manuel Cajigal','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>310,'municipio'=>'José Gregorio Monagas','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>311,'municipio'=>'Libertad','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>312,'municipio'=>'Manuel Ezequiel Bruzual','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>313,'municipio'=>'Pedro María Freites','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>314,'municipio'=>'Píritu','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>315,'municipio'=>'San José De Guanipa','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>316,'municipio'=>'San Juan De Capistrano','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>317,'municipio'=>'Santa Ana','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>318,'municipio'=>'Simón Bolívar','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>319,'municipio'=>'Simón Rodríguez','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>320,'municipio'=>'Sir Arthur Mc Gregor','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>321,'municipio'=>'Turístico Diego Bautista Urbaneja','id_estado'=>3,]);
        DB::table('municipio')->insert(['id'=>401,'municipio'=>'Achaguas','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>402,'municipio'=>'Biruaca','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>403,'municipio'=>'Muñoz','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>404,'municipio'=>'Páez','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>405,'municipio'=>'Pedro Camejo','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>406,'municipio'=>'Rómulo Gallegos','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>407,'municipio'=>'San Fernando','id_estado'=>4,]);
        DB::table('municipio')->insert(['id'=>501,'municipio'=>'Bolívar','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>502,'municipio'=>'Camatagua','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>503,'municipio'=>'Girardot','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>504,'municipio'=>'José Angel Lamas','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>505,'municipio'=>'José Félix Ribas','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>506,'municipio'=>'José Rafael Revenga','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>507,'municipio'=>'Libertador','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>508,'municipio'=>'Mario Briceño Iragorry','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>509,'municipio'=>'San Casimiro','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>510,'municipio'=>'San Sebastián','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>511,'municipio'=>'Santiago Mariño','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>512,'municipio'=>'Santos Michelena','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>513,'municipio'=>'Sucre','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>514,'municipio'=>'Tovar','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>515,'municipio'=>'Urdaneta','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>516,'municipio'=>'Zamora','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>517,'municipio'=>'Francisco Linares Alcántara','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>518,'municipio'=>'Ocumare De La Costa De Oro','id_estado'=>5,]);
        DB::table('municipio')->insert(['id'=>601,'municipio'=>'Alberto Arvelo Torrealba','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>602,'municipio'=>'Antonio José De Sucre','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>603,'municipio'=>'Arismendi','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>604,'municipio'=>'Barinas','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>605,'municipio'=>'Bolívar','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>606,'municipio'=>'Cruz Paredes','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>607,'municipio'=>'Ezequiel Zamora','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>608,'municipio'=>'Obispos','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>609,'municipio'=>'Pedraza','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>610,'municipio'=>'Rojas','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>611,'municipio'=>'Sosa','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>612,'municipio'=>'Andrés Eloy Blanco','id_estado'=>6,]);
        DB::table('municipio')->insert(['id'=>701,'municipio'=>'Caroní','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>702,'municipio'=>'Cedeño','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>703,'municipio'=>'El Callao','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>704,'municipio'=>'Gran Sabana','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>705,'municipio'=>'Heres','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>706,'municipio'=>'Piar','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>707,'municipio'=>'Bolivariano Angostura','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>708,'municipio'=>'Roscio','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>709,'municipio'=>'Sifontes','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>710,'municipio'=>'Sucre','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>711,'municipio'=>'Padre Pedro Chien','id_estado'=>7,]);
        DB::table('municipio')->insert(['id'=>801,'municipio'=>'Bejuma','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>802,'municipio'=>'Carlos Arvelo','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>803,'municipio'=>'Diego Ibarra','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>804,'municipio'=>'Guacara','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>805,'municipio'=>'Juan José Mora','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>806,'municipio'=>'Libertador','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>807,'municipio'=>'Los Guayos','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>808,'municipio'=>'Miranda','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>809,'municipio'=>'Montalbán','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>810,'municipio'=>'Naguanagua','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>811,'municipio'=>'Puerto Cabello','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>812,'municipio'=>'San Diego','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>813,'municipio'=>'San Joaquín','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>814,'municipio'=>'Valencia','id_estado'=>8,]);
        DB::table('municipio')->insert(['id'=>901,'municipio'=>'Anzoátegui','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>902,'municipio'=>'Falcón','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>903,'municipio'=>'Girardot','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>904,'municipio'=>'Lima Blanco','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>905,'municipio'=>'Pao De San Juan Bautista','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>906,'municipio'=>'Ricaurte','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>907,'municipio'=>'Rómulo Gallegos','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>908,'municipio'=>'Ezequiel Zamora','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>909,'municipio'=>'Tinaco','id_estado'=>9,]);
        DB::table('municipio')->insert(['id'=>1001,'municipio'=>'Antonio Díaz','id_estado'=>10,]);
        DB::table('municipio')->insert(['id'=>1002,'municipio'=>'Casacoima','id_estado'=>10,]);
        DB::table('municipio')->insert(['id'=>1003,'municipio'=>'Pedernales','id_estado'=>10,]);
        DB::table('municipio')->insert(['id'=>1004,'municipio'=>'Tucupita','id_estado'=>10,]);
        DB::table('municipio')->insert(['id'=>1101,'municipio'=>'Acosta','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1102,'municipio'=>'Bolívar','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1103,'municipio'=>'Buchivacoa','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1104,'municipio'=>'Cacique Manaure','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1105,'municipio'=>'Carirubana','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1106,'municipio'=>'Colina','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1107,'municipio'=>'Dabajuro','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1108,'municipio'=>'Democracia','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1109,'municipio'=>'Falcón','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1110,'municipio'=>'Federación','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1111,'municipio'=>'Jacura','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1112,'municipio'=>'Los Taques','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1113,'municipio'=>'Mauroa','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1114,'municipio'=>'Miranda','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1115,'municipio'=>'Monseñor Iturriza','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1116,'municipio'=>'Palmasola','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1117,'municipio'=>'Petit','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1118,'municipio'=>'Piritu','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1119,'municipio'=>'San Francisco','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1120,'municipio'=>'Silva','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1121,'municipio'=>'Sucre','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1122,'municipio'=>'Tocópero','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1123,'municipio'=>'Unión','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1124,'municipio'=>'Urumaco','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1125,'municipio'=>'Zamora','id_estado'=>11,]);
        DB::table('municipio')->insert(['id'=>1201,'municipio'=>'Camaguán','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1202,'municipio'=>'Chaguaramas','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1203,'municipio'=>'El Socorro','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1204,'municipio'=>'San Gerónimo De Guayabal','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1205,'municipio'=>'Leonardo Infante','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1206,'municipio'=>'Las Mercedes','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1207,'municipio'=>'Julián Mellado','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1208,'municipio'=>'Francisco De Miranda','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1209,'municipio'=>'José Tadeo Monagas','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1210,'municipio'=>'Ortiz','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1211,'municipio'=>'José Félix Ribas','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1212,'municipio'=>'Juan Germán Roscio','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1213,'municipio'=>'San José De Guaribe','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1214,'municipio'=>'Santa María De Ipire','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1215,'municipio'=>'Pedro Zaraza','id_estado'=>12,]);
        DB::table('municipio')->insert(['id'=>1301,'municipio'=>'Andrés Eloy Blanco','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1302,'municipio'=>'Crespo','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1303,'municipio'=>'Iribarren','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1304,'municipio'=>'Jiménez','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1305,'municipio'=>'Morán','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1306,'municipio'=>'Palavecino','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1307,'municipio'=>'Simón Planas','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1308,'municipio'=>'Torres','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1309,'municipio'=>'Urdaneta','id_estado'=>13,]);
        DB::table('municipio')->insert(['id'=>1401,'municipio'=>'Alberto Adriani','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1402,'municipio'=>'Andrés Bello','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1403,'municipio'=>'Antonio Pinto Salinas','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1404,'municipio'=>'Aricagua','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1405,'municipio'=>'Arzobispo Chacón','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1406,'municipio'=>'Campo Elías','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1407,'municipio'=>'Caracciolo Parra Olmedo','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1408,'municipio'=>'Cardenal Quintero','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1409,'municipio'=>'Guaraque','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1410,'municipio'=>'Julio César Salas','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1411,'municipio'=>'Justo Briceño','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1412,'municipio'=>'Libertador','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1413,'municipio'=>'Miranda','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1414,'municipio'=>'Obispo Ramos De Lora','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1415,'municipio'=>'Padre Noguera','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1416,'municipio'=>'Pueblo Llano','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1417,'municipio'=>'Rangel','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1418,'municipio'=>'Rivas Dávila','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1419,'municipio'=>'Santos Marquina','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1420,'municipio'=>'Sucre','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1421,'municipio'=>'Tovar','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1422,'municipio'=>'Tulio Febres Cordero','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1423,'municipio'=>'Zea','id_estado'=>14,]);
        DB::table('municipio')->insert(['id'=>1501,'municipio'=>'Acevedo','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1502,'municipio'=>'Andrés Bello','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1503,'municipio'=>'Baruta','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1504,'municipio'=>'Brión','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1505,'municipio'=>'Buroz','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1506,'municipio'=>'Carrizal','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1507,'municipio'=>'Chacao','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1508,'municipio'=>'Cristóbal Rojas','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1509,'municipio'=>'El Hatillo','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1510,'municipio'=>'Bolivariano Guaicaipuro','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1511,'municipio'=>'Independencia','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1512,'municipio'=>'Lander','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1513,'municipio'=>'Los Salias','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1514,'municipio'=>'Páez','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1515,'municipio'=>'Paz Castillo','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1516,'municipio'=>'Pedro Gual','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1517,'municipio'=>'Plaza','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1518,'municipio'=>'Simón Bolívar','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1519,'municipio'=>'Sucre','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1520,'municipio'=>'Urdaneta','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1521,'municipio'=>'Zamora','id_estado'=>15,]);
        DB::table('municipio')->insert(['id'=>1601,'municipio'=>'Acosta','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1602,'municipio'=>'Aguasay','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1603,'municipio'=>'Bolívar','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1604,'municipio'=>'Caripe','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1605,'municipio'=>'Cedeño','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1606,'municipio'=>'Ezequiel Zamora','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1607,'municipio'=>'Libertador','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1608,'municipio'=>'Maturín','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1609,'municipio'=>'Piar','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1610,'municipio'=>'Punceres','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1611,'municipio'=>'Santa Bárbara','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1612,'municipio'=>'Sotillo','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1613,'municipio'=>'Uracoa','id_estado'=>16,]);
        DB::table('municipio')->insert(['id'=>1701,'municipio'=>'Antolín Del Campo','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1702,'municipio'=>'Arismendi','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1703,'municipio'=>'Díaz','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1704,'municipio'=>'García','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1705,'municipio'=>'Gómez','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1706,'municipio'=>'Maneiro','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1707,'municipio'=>'Marcano','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1708,'municipio'=>'Mariño','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1709,'municipio'=>'Península De Macanao','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1710,'municipio'=>'Tubores','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1711,'municipio'=>'Villalba','id_estado'=>17,]);
        DB::table('municipio')->insert(['id'=>1801,'municipio'=>'Agua Blanca','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1802,'municipio'=>'Araure','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1803,'municipio'=>'Esteller','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1804,'municipio'=>'Guanare','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1805,'municipio'=>'Guanarito','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1806,'municipio'=>'Monseñor José Vicente De Unda','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1807,'municipio'=>'Ospino','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1808,'municipio'=>'Páez','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1809,'municipio'=>'Papelón','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1810,'municipio'=>'San Genaro De Boconoito','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1811,'municipio'=>'San Rafael De Onoto','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1812,'municipio'=>'Santa Rosalía','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1813,'municipio'=>'Sucre','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1814,'municipio'=>'Turén','id_estado'=>18,]);
        DB::table('municipio')->insert(['id'=>1901,'municipio'=>'Andrés Eloy Blanco','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1902,'municipio'=>'Andrés Mata','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1903,'municipio'=>'Arismendi','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1904,'municipio'=>'Benítez','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1905,'municipio'=>'Bermúdez','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1906,'municipio'=>'Bolívar','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1907,'municipio'=>'Cajigal','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1908,'municipio'=>'Cruz Salmerón Acosta','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1909,'municipio'=>'Libertador','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1910,'municipio'=>'Mariño','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1911,'municipio'=>'Mejía','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1912,'municipio'=>'Montes','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1913,'municipio'=>'Ribero','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1914,'municipio'=>'Sucre','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>1915,'municipio'=>'Valdez','id_estado'=>19,]);
        DB::table('municipio')->insert(['id'=>2001,'municipio'=>'Andrés Bello','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2002,'municipio'=>'Antonio Rómulo Costa','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2003,'municipio'=>'Ayacucho','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2004,'municipio'=>'Bolívar','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2005,'municipio'=>'Cárdenas','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2006,'municipio'=>'Córdoba','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2007,'municipio'=>'Fernández Feo','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2008,'municipio'=>'Francisco De Miranda','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2009,'municipio'=>'García De Hevia','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2010,'municipio'=>'Guásimos','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2011,'municipio'=>'Independencia','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2012,'municipio'=>'Jáuregui','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2013,'municipio'=>'José María Vargas','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2014,'municipio'=>'Junín','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2015,'municipio'=>'Libertad','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2016,'municipio'=>'Libertador','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2017,'municipio'=>'Lobatera','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2018,'municipio'=>'Michelena','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2019,'municipio'=>'Panamericano','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2020,'municipio'=>'Pedro María Ureña','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2021,'municipio'=>'Rafael Urdaneta','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2022,'municipio'=>'Samuel Darío Maldonado','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2023,'municipio'=>'San Cristóbal','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2024,'municipio'=>'Seboruco','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2025,'municipio'=>'Simón Rodríguez','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2026,'municipio'=>'Sucre','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2027,'municipio'=>'Torbes','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2028,'municipio'=>'Uribante','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2029,'municipio'=>'San Judas Tadeo','id_estado'=>20,]);
        DB::table('municipio')->insert(['id'=>2101,'municipio'=>'Andrés Bello','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2102,'municipio'=>'Boconó','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2103,'municipio'=>'Bolívar','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2104,'municipio'=>'Candelaria','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2105,'municipio'=>'Carache','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2106,'municipio'=>'Escuque','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2107,'municipio'=>'José Felipe Márquez Cañizales','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2108,'municipio'=>'Juan Vicente Campo Elías','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2109,'municipio'=>'La Ceiba','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2110,'municipio'=>'Miranda','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2111,'municipio'=>'Monte Carmelo','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2112,'municipio'=>'Motatán','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2113,'municipio'=>'Pampán','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2114,'municipio'=>'Pampanito','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2115,'municipio'=>'Rafael Rangel','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2116,'municipio'=>'San Rafael De Carvajal','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2117,'municipio'=>'Sucre','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2118,'municipio'=>'Trujillo','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2119,'municipio'=>'Urdaneta','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2120,'municipio'=>'Valera','id_estado'=>21,]);
        DB::table('municipio')->insert(['id'=>2201,'municipio'=>'Arístides Bastidas','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2202,'municipio'=>'Bolívar','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2203,'municipio'=>'Bruzual','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2204,'municipio'=>'Cocorote','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2205,'municipio'=>'Independencia','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2206,'municipio'=>'José Antonio Páez','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2207,'municipio'=>'La Trinidad','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2208,'municipio'=>'Manuel Monge','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2209,'municipio'=>'Nirgua','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2210,'municipio'=>'Peña','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2211,'municipio'=>'San Felipe','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2212,'municipio'=>'Sucre','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2213,'municipio'=>'Urachiche','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2214,'municipio'=>'Veroes','id_estado'=>22,]);
        DB::table('municipio')->insert(['id'=>2301,'municipio'=>'Almirante Padilla','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2302,'municipio'=>'Baralt','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2303,'municipio'=>'Cabimas','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2304,'municipio'=>'Catatumbo','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2305,'municipio'=>'Colón','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2306,'municipio'=>'Francisco Javier Pulgar','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2307,'municipio'=>'Jesús Enrique Lossada','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2308,'municipio'=>'Jesús María Semprún','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2309,'municipio'=>'La Cañada De Urdaneta','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2310,'municipio'=>'Lagunillas','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2311,'municipio'=>'Machiques De Perijá','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2312,'municipio'=>'Mara','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2313,'municipio'=>'Maracaibo','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2314,'municipio'=>'Miranda','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2315,'municipio'=>'Indǵrna Bolivariano Guajira','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2316,'municipio'=>'Rosario De Perijá','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2317,'municipio'=>'San Francisco','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2318,'municipio'=>'Santa Rita','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2319,'municipio'=>'Simón Bolívar','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2320,'municipio'=>'Sucre','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2321,'municipio'=>'Valmore Rodríguez','id_estado'=>23,]);
        DB::table('municipio')->insert(['id'=>2401,'municipio'=>'Vargas','id_estado'=>24,]);
        DB::table('municipio')->insert(['id'=>2501,'municipio'=>'Dependencias Federales','id_estado'=>25,]);
    }
}
